algoritmo "projeto 2"
// Função :
// Autor :
// Data : 06/08/2018
// Seção de Declarações 
var
   n1,n2, d, t:inteiro
inicio
      Escreval ("Boa noite !!")
      Escreva ("Insira o primeiro número: ")
      Leia (n1)
      Escreva ("Insira o segundo numero: ")
      Leia (n2)
      
      d<- n1*2
      t<- n2*3
      
      Escreval ("O duplo do primeiro é: ", d)

      Escreva (" O triplo do segundo é: ", t)

      
      
      



fimalgoritmo
